### ISSUE TITLE
XML files

### ISSUE THREAD

**Issue by Zeyadramadan1** [vijaydwivedi75/Custom-Mask-RCNN_TF#1]
thank you for the tutorial it is very helpful.

I have one question though, how did you create the XML files 

thanks in advance

**Comment by vijaydwivedi75** [comment]
Hi @Zeyadramadan1, the XML files should also be the output of the Pixel Annotation Tool while you annotate the masks of the dataset.

Thanks!

**Comment by vijaydwivedi75** [comment]
Closing the issue!
